name: liberdeck
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  flutter_staggered_grid_view: ^0.4.0
  font_awesome_flutter: ^9.1.0
  google_sign_in: ^5.1.0
  pdf_render: ^1.0.13
  provider: ^6.0.0
  url_launcher: null

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
    
  lint: ^1.6.0
flutter_icons:
  image_path: 'assets/images/google.png'
  android: true
  ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
