name: liberdeck
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.1
  google_sign_in: ^5.1.0
  firebase_core: ^1.6.0
  provider: ^6.0.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  font_awesome_flutter: ^9.1.0
  url_launcher:
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.6.0

flutter:
  uses-material-design: true

  assets:

    - assets/
    - assets/images/
    - assets/fonts/

